name: bintex_mobile_driver
description: driver app

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  #state management
  stacked: ^1.7.6

  #navigation
  auto_route: 
  stacked_services: ^0.6.0+1

  #inversion of control
  get_it:
  injectable:

  #svg
  flutter_svg:

  #http
  http: ^0.12.2

  #email validator
  email_validator: ^1.0.6

  #path
  path_provider: ^1.6.24

  #type ahead in add page
  flutter_typeahead: ^1.9.1

  # spinkit for loading animation
  flutter_spinkit: "^4.1.2"

dev_dependencies:
  flutter_launcher_icons: ^0.8.1

  flutter_test:
    sdk: flutter

  build_runner:
  auto_route_generator:
  injectable_generator:

flutter:
  uses-material-design: true

  assets:
    - lib/assets/image/auth_header/
    - lib/assets/image/auth_body/
    - lib/assets/image/home/

  fonts:
    - family: CrimsonText
      fonts:
      - asset: lib/assets/font/CrimsonText-Regular.ttf
      - asset: lib/assets/font/CrimsonText-SemiBold.ttf
        weight: 600

    - family: OpenSans
      fonts:
      - asset: lib/assets/font/OpenSans-Regular.ttf
        style: normal
      - asset: lib/assets/font/OpenSans-SemiBold.ttf
        weight: 600

flutter_icons:
  ios: true
  android: true
  image_path_ios: "lib/assets/launcher/icon.png"
  image_path_android: "lib/assets/launcher/icon.png"
  adaptive_icon_background: "lib/assets/launcher/background.png"
  adaptive_icon_foreground: "lib/assets/launcher/foreground.png"